version: '3.8'

services:
  plate-detector:
    container_name: plate-detector
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${DETECTED_PATH}:/app/detected
      - ${LOGS_PATH}:/app/logs
      - ${WATCHLIST_PATH}:/app/plates_watchlist.json:ro
    ports:
      - "5000:5000"
